-- custom sql

-- PRODUCTS
INSERT INTO BLC_PRODUCT (PRODUCT_ID, URL, MANUFACTURE, IS_FEATURED_PRODUCT) VALUES (200000, '/whellwrech/tentierwrench', 'PrakashENWorks''s',TRUE);

-- search attributes
-- INSERT INTO BLC_PRODUCT_OPTION (PRODUCT_OPTION_ID, OPTION_TYPE, ATTRIBUTE_NAME, LABEL, REQUIRED) VALUES (400000, 'ITEMSIZE', 'ITEMSIZE', 'Item Size', TRUE);




