--custom for rent your stuff- Level 0 -main category
INSERT INTO BLC_CATEGORY (CATEGORY_ID,DESCRIPTION,NAME,URL,ACTIVE_START_DATE) VALUES (1000,'Automobile','Automobile','/automobile',CURRENT_TIMESTAMP);
--custom for rent your stuff-Level 1 sub-category
INSERT INTO BLC_CATEGORY (CATEGORY_ID,DESCRIPTION,NAME,URL,ACTIVE_START_DATE) VALUES (1100,'Spanners','Spanners','/spanners',CURRENT_TIMESTAMP);
----custom for rent your stuff-Level 2 sub-category
INSERT INTO BLC_CATEGORY (CATEGORY_ID,DESCRIPTION,NAME,URL,ACTIVE_START_DATE) VALUES (1110,'Tata','Tata','/tata',CURRENT_TIMESTAMP);

--custom for rent your stuff - mapping between Level 1 and Level 0
INSERT INTO BLC_CATEGORY_XREF (CATEGORY_XREF_ID, SUB_CATEGORY_ID, CATEGORY_ID, DISPLAY_ORDER, DEFAULT_REFERENCE) VALUES (9000,1100,1000,1,TRUE);

--custom for rent your stuff - mapping between Level 2 and Level 1

INSERT INTO BLC_CATEGORY_XREF (CATEGORY_XREF_ID, SUB_CATEGORY_ID, CATEGORY_ID,DISPLAY_ORDER,DEFAULT_REFERENCE ) SELECT MAX( CATEGORY_XREF_ID )+1,1110,1100,1,true FROM BLC_CATEGORY_XREF;


